var preloaded = [
    {f: "FLASHBACK-DROGER", s: "Det kommer garanterat att fungera galant. Om det inte fungerar, se till att dricka 4-6 starköl innan gåsen."},
    {f: "FLASHBACK-DROGER",   s: "Jogga/träna varje dag samt ha regelbundna sovtider, gå alltid upp klockan 07 och gå och lägg dig 22, då ska du se att det fungerar.",},
    {f: "FLASHBACK-DROGER", s: "Sluta bara i Sverige.. Om det var sant skulle fan Holland ha mest trafikolyckor i världen, men oftast så är ju svensk forskning bäst och utländsk forskning kass.."},
    {f: "FLASHBACK-DROGER", s: "Det blir lättare att tänka positivt när man ej blazar varje dag och det blir lättare att ta sej genom såna här dryga grejer om man tänker positivt"},
    {f: "FLASHBACK-DROGER", s: "Har försökt få tag på chefen där utan resultat, eftersom de kör med bemanningsföretag och bytte känns det ändå rätt lönlöst nu när jag ändå blivit nekad anställning av dem."},
    {f: "FLASHBACK-DROGER", s: "tja, dina sinnen har väl förstärkts på nåt vis, men sådär har jag typ hela tiden utan gösen, men så har jag också adhd typ."},
    {f: "FLASHBACK-DROGER", s: "Jag har haft extrem ljudkännslighet även nykter, dvs hyperakusi."},
    {f: "FAMILJELIV-ALLMANNA-SANDLADAN", s: "Du får väl bli en hen, det r ju inne nuförtiden."},
    {f: "FAMILJELIV-ALLMANNA-SANDLADAN", s: "Jag har haft hunden i tre veckor och nu orkar jag inte mer."},
    {f: "FAMILJELIV-ALLMANNA-SANDLADAN", s: "Säg att du skrev detta för att du har en allmänt tråkig fredag bara??"},
    {f: "FAMILJELIV-ALLMANNA-SANDLADAN", s: "Att lapa pastasås tätt ovanpå platån passar en nomad."},
    {f: "FAMILJELIV-ALLMANNA-SANDLADAN", s: "Fyll ormskinnsväskorna rikligt med aceton, Tekla Ingemarsson, och njut."},
    {f: "FAMILJELIV-ALLMANNA-SANDLADAN", s: "Jag har i flera år haft ett problem, nämligen att jag kissar ner mig i sömnen."},
    {f: "FAMILJELIV-ALLMANNA-SANDLADAN", s: "Har du varit hos en läkare? Om inte, boka tid snarast!"},
    {f: "FAMILJELIV-ALLMANNA-SANDLADAN", s: "Om inte ge fan i och hänga ut dom och dessutom dra alla vita medelålders män över en kam."},
    {f: "FAMILJELIV-ALLMANNA-SAMHALLE", s: "Nyligen tyckte en österrikisk politiker att Tysklands förbundskansler Angela Merkel bara därför vill ta emot flyktlingar eftersom hon inte ha egna barn."},
    {f: "FAMILJELIV-ALLMANNA-SAMHALLE", s: "En annan grej i diskussionen kan ju sen vara när det ska födda första barnet. ..."},
    {f: "FAMILJELIV-ALLMANNA-SAMHALLE", s: "Han fick dock lämna sitt parti dvs. blev utsluten ur konservativa partiet där han sist var medlem."},
    {f: "FLASHBACK-OVRIGT", s: "Klättra frisolo på en stor klippa, släpp taget vid önskad höjd."},
    {f: "FLASHBACK-OVRIGT", s: "Sätt på plattan undernatten med en stekpanna med lite olja, häng jul saker (sånt som tar eld) ovanför spisen, men inte så att der ser sjukt ut."},
    {f: "FLASHBACK-OVRIGT", s: "fnissa sedan över att tjyvens kolesterolvärde går åt pipan."},
    {f: "FLASHBACK-OVRIGT", s: "Blir jag kollad uppger jag helt enkelt mina uppgifter, tjaffsar lite lagom, ger fan i att visa nån legitimation och drar en ful kråka på lappen, sen river jag inbetalningskortet och slänger i närmsta papperskorg."},
    {f: "FLASHBACK-OVRIGT", s: "Det är något med Göteborg som jag inte litar på, allt känns bara som en fasad, människorna känns inte som individer utan som något typ av sektmedlemmar framavlade i generationer. "},
    {f: "FLASHBACK-OVRIGT", s: "Det är likadant med norrmännen, ett vedervärdigt mindervärdeskomplex gentemot oss svenskar..."},
    {f: "FLASHBACK-OVRIGT", s: "Hej, det här med att dra upp saker man gjorde när man var ung och dum, hur ser ni på det?"},
    {f: "FAMILJELIV-EXPERT", s: "Sen har jag även svårt att få i mig luft enligt min sambo låter jag mega andfådd även om jag har bara legat i soffan och tagit lugnt.. "},
    {f: "FAMILJELIV-EXPERT", s: "Sedan vid 8 tiden tog jag ett till och de visade antydan/svagtstreck igen?!"},
    {f: "FAMILJELIV-EXPERT", s: "Det står att man ska skriva i procent, är det då procent av den lön man har eller på föräldrapenningen?"},
    {f:"FAMILJELIV-ALLMANNA-SAMHALLE", s: "I julas kom han hem från dagis och talade om att en del tror på tomten, andra på alver och några tror på gud."},
    {f: "FAMILJELIV-ALLMANNA-SAMHALLE",s: "Synd att du inte kan skilja på sak och person utan bygger all din argumentation på halmgubbar."},
    {f: "FLASHBACK-SPORT",s: "Mycket bra genomförd stafett av svenskorna."},
    {f: "FAMILJELIV-ANGLARUM",s: "Nu är det över Det var visst bara när det handlade i regel om gängkrigen man fick vittna i ett annat rum ... :S Nu väntar jag bara på domen."},
    {f: "FAMILJELIV-ALLMANNA-EKONOMI",s: "Vi blev nyfikna på hur ekonomin ser ut runt 45 år och vilka problem som kan finnas då."},
    {f: "FAMILJELIV-ALLMANNA-HUSDJUR",s: "Han vägrar bajsa i den så han har ICAs kattsand, men jag tycker det luktar så jäkligt av den när han gjort sina behov .."},
    {f: "FLASHBACK-FLASHBACK",s: "Katten är ju menlös."},
    {f: "FLASHBACK-LIVSSTIL",s: "Varför ska du ut och roa dig när du kan donera ännu mer pengar till välgörenhet?"},
    {f: "FLASHBACK-OVRIGT",s: "* klunk klunk klunk * låter juicen tills jag kommer på att jag redan slängt ett paket!!"},
    {f: "FAMILJELIV-ALLMANNA-KROPP",s: "Jag har vänninor som kört lite olika behandlingar och en som kört cavi-lipo och är nöjd."},
    {f: "FLASHBACK-LIVSSTIL",s: "Jag tror att nya fjortis modet har blivit reflexjacka / väst!"},
    {f: "FAMILJELIV-ALLMANNA-FRITID",s: "får man även använda den gröna drinken som föryngrar??"},
    {f: "FLASHBACK-MAT",s: "Sist blev det en halva fläskfile med kantareller på burk samt rödlök och creme freache, lite timjan och kalvfond(stavning?)"},
    {f: "FAMILJELIV-ALLMANNA-HUSHEM",s: "Dragonfisk med ris igår och idag blev det spökkyckling med nudlar."},
    {f: "FAMILJELIV-ANGLARUM", s: "Att lägga sitt eget barn i en kista är det värsta man kan göra i livet!"},
    {f: "FLASHBACK-RESOR", s: "Finns ett gäng tv-serier också, 2-3 avsnitt av serier som Big Bang, Sunny in P, Adventures of New Christine osv."},
    {f: "FLASHBACK-RESOR", s: "Jag har kompisar från Nagoya och både staden och universitetet har ett got rykte."},
    {f: "FAMILJELIV-ADOPTION", s: "Så jag undrar om det är nån mer här som har förnyat / uppdaterat sin hemutredning efter att den nya handboken kommit."},
    {f: "FAMILJELIV-ANGLARUM", s: "Ponea : du fick mitt beslut till planerat snitt att kännas ännu mer vettigt eftersom min moderkaka lossnat två ggr har jag ökad risk att det ska hända igen."},
    {f: "FAMILJELIV-EXPERT", s: "X kissar i sin hand och får kortet."},
    {f: "FAMILJELIV-EXPERT", s: "det är inte meningen man ska må såhär dåligt!"},
    {f: "FLASHBACK-RESOR", s: "inte kliva av bilen för annat än tankning på hela vägen / done that!"},
    {f: "FLASHBACK-FLASHBACK", s: "Javisst och rensa bort knarkdelen!"},
    {f: "FAMILJELIV-PAPPAGRUPP", s: "Var med min fästmö på inskrivning imorse."},
    {f: "FAMILJELIV-PAPPAGRUPP", s: "Smidigast är att ha en stor låda."},
    {f: "FLASHBACK-FLASHBACK", s: "Den här tråden handlar så vitt jag kan se om regelverket."},
    {f: "FAMILJELIV-EXPERT", s: "Du kan välja vilken välling du vill till en fyra-femåring."},
    {f: "FAMILJELIV-ADOPTION", s: "Så so mjag förstått det så är den sk 43-års regeln ännu under utredning?"},
    {f: "FAMILJELIV-ADOPTION", s: "'Lösningen' blev att pappan inte fick vara hemma på heltid alls, och att du var hemma på heltid i början med båda barnen, trots att pappan tydligen ville vara hemma."},
    {f: "FAMILJELIV-ANGLARUM", s: "Känns inte som relevant att förklara för mycket för barnen,,, beror förstås på ålder."},
    {f: "FAMILJELIV-PAPPAGRUPP", s: "Fega miffon tar bort en del av nöjet..."},
    {f: "FAMILJELIV-PAPPAGRUPP", s: "Hennes lediga dagar går mestadels ut på att sitta framför datorn eller framför spisfläkten och röka."},
    {f: "FAMILJELIV-PAPPAGRUPP", s: "Alla pappor som är sugna på att träffa lite nytt folk, utbyta tankar och ideer, hitta på roliga saker är välkomna in i gruppen pappaor i småland på facebook.."},
    {f: "FLASHBACK-FLASHBACK", s: "RP:ad av en annan användare, troligtvis har inte mod hunnit titta på den än."},
    {f: "FAMILJELIV-ANGLARUM", s: "Precis innan vi åkte ner läste jag i tidningen om biskopsbrevet om pastoral akt o kände att det skulle jag velat ha, skulle vilja haft mer av ett avslut."},
    {f: "FAMILJELIV-PAPPAGRUPP", s: "Är själv medlem i svenska kyrkan fortfarande(trots kostnaden) men mer för dess ceremoniella värde än för att jag tror på budskapet."},
    {f: "FAMILJELIV-EXPERT", s: "Har då tagit tabletterna under 4-5 veckor ca."},
    {f: "FLASHBACK-FLASHBACK", s: "Tillägg : Kanske i Ekologi, natur, djur och växter?"},
    {f: "FAMILJELIV-EXPERT", s: "Tycker du att de gör ont kan du prova med lite Alvedon eller att vila en stund när du har möjlighet."},
    {f: "FLASHBACK-FLASHBACK", s: "Jag tycker det idag sköter sig självt lite genom att trådar där diskussionen är 'alla-mot-en' stannar upp när den ensamme debattören inte skriver i den."},
    {f: "FAMILJELIV-PAPPAGRUPP", s: "Speciellt när man nu träffar alla vänner som kommer med sina nyfödda!"},
    {f: "FLASHBACK-FLASHBACK", s: "Tror inte att det är någon bra lösning att tabubelägga det."},
    {f: "FLASHBACK-FLASHBACK", s: "Är det ett ämne som berör folk i övrigt, och får dem att vilja regga sig på FB för att debatttera ämnet?"},
    {f: "FAMILJELIV-PAPPAGRUPP", s: "Babyproffsen har olika vagnar, men var har råd till en sån vagn?"},
    {f: "FAMILJELIV-EXPERT", s: "Hon frågade mig om jag har fött barn, och det har jag ju inte."},
    {f: "FAMILJELIV-ANGLARUM", s: "Är det någon här som ska på spädbarnsfondens tema dag på torsdag?!"},
    {f: "FLASHBACK-FLASHBACK", s: "Syftet har aldrig varit att vara underground utan att det var underground var egentligen symptomet på det grundläggande felet."},
    {f: "FAMILJELIV-PAPPAGRUPP", s: "Det började under graviditeten och fortsatte under en ganska lång tid."},
    {f: "FLASHBACK-FLASHBACK", s: "Vi vill inte att detta förvandlas till ett nytt Fragbite..."},
    {f: "FAMILJELIV-EXPERT", s: "Varför bedriver socialdemokraterna en företagsfientlig politik?"},
    {f: "FAMILJELIV-ALLMANNA-FRITID", s: "Priset beror på hur stor ytan är, vad ni vill ha hjälp med och hur lång tid det tar."},
    {f: "FLASHBACK-FLASHBACK", s: "Skönt att vi är rörande överens."},
    {f: "FAMILJELIV-ALLMANNA-FRITID", s: "Förstår inte hur level 79"},
    {f: "FAMILJELIV-ALLMANNA-FRITID", s: "Nu kastade jag filen, som komiskt nog tillhörde installationen till virusprogrammet... eller var det något som ville få mig att tro det?"},
    {f: "FLASHBACK-DROGER", s: "Du är ung och gjorde ett misstag"},
    {f: "FLASHBACK-DROGER", s: "Hon kanske inte har kollat eller förståt vad hon hittat"},
    {f: "FLASHBACK-DROGER", s: "Du har satt dig själv i skiten och hon ska få skyffla lite mer innan ni kan städa bort allt."},
    {f: "FLASHBACK-DROGER", s: "Vad vill du att vi ska göra, prata med din mor?"},
    {f: "FLASHBACK-VETENSKAP", s: "Samtidigt ska första steget från Orbcomm-2 testas på LC-40 imorgon."},
    {f: "FLASHBACK-VETENSKAP", s: "Alla ovanstående, man använder sk död räkning med gyron, denna assisteras av GPS, Även andrasteget använder gyro + GPS för att placera payloaden i så precis bana som möjligt."},
    {f: "FLASHBACK-VETENSKAP", s: "Nu är tandköttet på högra sidan ganska svullet, kanske för att jag borstade för hårt?"},
    {f: "FLASHBACK-VETENSKAP", s: "Drick whiskey och vodka och ha kvar det så länge som möjligt i munnen, du kommer ej känna smärtan och infektionen behandlas, ifall du har käka antibiotika."},
    {f: "FLASHBACK-VETENSKAP", s: "Han kommer bli 172,5 cm lång när han är 19 och ett halvt."},
    {f: "FLASHBACK-VETENSKAP", s: "Min syster har de senaste 3 veckor haft ont i huvudet,hon beskriver det som ett tryck i bak."},
    {f: "FLASHBACK-VETENSKAP", s: "Jag tycker ofta man stöter på böjningar i media som känns rätt malplacerade, och tanken med tråden är att man kan ta upp sådana och få svar på om det är det egna språkörat det är fel på eller om språket helt enkelt behandlats fel.."},
    {f: "FLASHBACK-VETENSKAP", s: "Gäst verkar ha varit ett modeord bland germaner på folkvandringstiden."},
    {f: "FLASHBACK-OVRIGT", s: "Jag bjuder dig och upp till sju vänner på en kryssning (två hytter) inkl bussanslutning."},
    {f: "FLASHBACK-OVRIGT", s: "Skall tydligen vara 1000 testpiloter som fått denna kod av vad jag har läst."},
    {f: "FLASHBACK-OVRIGT", s: "Funkar dom i en vanlig Nespresso, om dom är från Lidl?"},
    {f: "FLASHBACK-OVRIGT", s: "Har lagt ner ett projekt på grund av flytt till Spanien och behöver bli av med dessa prylar omgående, senast imorgon."},
];